language: node_js
node_js:
  - 7
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install

jobs:
  include:
    - stage: lint
      script:
        - yarn run lint
    - stage: test
      script:
        - yarn run test
        - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    - stage: build
      script:
        - yarn run build
      deploy:
        provider: npm
        email: xyan.sk@gmail.com
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
